version: '3.9'

services:
  proxy:
    container_name: "nginx-proxy"
    image: "nginx:latest"
    networks:
      - backend
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/

  web:
    container_name: "web-app"
    networks:
      - proxy
    build: ${WEB_BUILD_URL}

  auth-app:
    container_name: "auth-app"
    build: ${APP_AUTH_BUILD_URL}
    depends_on:
      - database
    networks:
      - backend

  messenger-app:
    container_name: "messenger-app"
    build: ${APP_MESSENGER_BUILD_URL}
    depends_on:
      - auth-app
      - database
      - notification
    networks:
      - backend

  notification:
    container_name: "notify-app"
    build: ${NOTIFY_BUILD_URL}
    depends_on:
      - database
    networks:
      - backend

  database:
    container_name: "mongo"
    image: "mongo:latest"
    networks:
      - backend
    volumes:
      - type: bind
        source: ./data
        target: /data/db

networks:
  backend:
  proxy: